### ISSUE TITLE
line-painter bug in writing document manifest

### ISSUE THREAD

**Issue by tacaswell** [bluesky/databroker-pack#29]
I have not checked if this reproduces on current main, but documenting so I don't forget.

Looking at a pretty big export (16k runs) I noticed the `document_manifest.txt` file was ~5.8G which seemed wrong.   The first couple lines of the file is:

```
147b431a-a326-4892-a4ae-a3127bc08f6c.msgpack
147b431a-a326-4892-a4ae-a3127bc08f6c.msgpack
922ed815-a5f8-4fe1-a5ac-a4c3893bf553.msgpack
147b431a-a326-4892-a4ae-a3127bc08f6c.msgpack
922ed815-a5f8-4fe1-a5ac-a4c3893bf553.msgpack
e0a8934b-c0cd-4b77-ad4b-5058cb21211b.msgpack
147b431a-a326-4892-a4ae-a3127bc08f6c.msgpack
922ed815-a5f8-4fe1-a5ac-a4c3893bf553.msgpack
e0a8934b-c0cd-4b77-ad4b-5058cb21211b.msgpack
9b4b9a84-151b-4c7c-854d-ebe33124a1de.msgpack
```

which shows we are re-writing the whole set of files everytime we add one which in turns what should be a 16498 line file into a 136100251 line file  ;)

**Comment by danielballan** [comment]
I remember seeing this and fixing it, or at least attempting to. The release notes for v0.2.0 include

> Fixed
> The documents_manifest.txt contained duplicate entries.

Can you reproduce on a version >=0.2.0?

**Comment by tacaswell** [comment]
```
    metadata:
      generated_by:
        library: databroker_pack
        version: 0.1.3
      relative_paths:
      - ./*.msgpack
```

:heart:  for thinking to drop the version number in the output.

Running a test with 0.3.0 but going to preemptively close this.
